import React, { useState, useMemo, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Star, Trash2, Share, Download, FileText, Loader2, Lightbulb, FolderOpen, Hash, Search, X, Volume2, VolumeX, Pencil, Save, XCircle, Brain } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from '@/components/ui/dropdown-menu';
import { useNotes } from '@/contexts/NotesContext';
import { formatDistanceToNow } from 'date-fns';
import SourcePreview from '@/components/SourcePreview';
import AITemplatesPanel from '@/components/AITemplatesPanel';
import NoteChat from '@/components/NoteChat';
import { toast } from 'sonner';
import { useTTS } from '@/hooks/useTTS';
import ReactMarkdown from 'react-markdown';
import { generateBriefSummary, generateActionItems } from '@/services/noteAIService';

const NoteDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { getNote, toggleStar, deleteNote, updateNote, folders, tags } = useNotes();
  const [activeTab, setActiveTab] = useState('overview');
  const [transcriptSearch, setTranscriptSearch] = useState('');
  const { speak, stop, isPlaying, isLoading: isTTSLoading } = useTTS();
  
  // Edit mode state
  const [isEditing, setIsEditing] = useState(false);
  const [editTitle, setEditTitle] = useState('');
  const [editContent, setEditContent] = useState('');
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  const hasAutoGenerated = useRef(false);
  
  const note = id ? getNote(id) : undefined;

  if (!note) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-center">
        <FileText className="h-16 w-16 text-muted-foreground mb-4" />
        <h2 className="text-xl font-semibold mb-2">Note not found</h2>
        <p className="text-muted-foreground mb-4">This note may have been deleted.</p>
        <Button onClick={() => navigate('/')}>
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back to Dashboard
        </Button>
      </div>
    );
  }

  const handleDelete = () => {
    deleteNote(note.id);
    toast.success('Note deleted');
    navigate('/');
  };

  const handleSaveAIOutput = (type: string, content: string) => {
    const updates: Record<string, any> = {};
    
    switch (type) {
      case 'summary':
        updates.summary = content;
        break;
      case 'actions':
        updates.actionItems = content.split('\n').filter((item) => item.trim());
        break;
      case 'bullets':
        updates.bulletedNotes = content;
        break;
      case 'minutes':
        updates.meetingMinutes = content;
        break;
      case 'email':
        updates.followUpEmail = content;
        break;
      case 'quiz':
        updates.quizContent = content;
        break;
    }
    
    if (Object.keys(updates).length > 0) {
      updateNote(note.id, updates);
      toast.success('Saved to note');
    }
  };

  // Edit mode handlers
  const handleStartEdit = () => {
    setEditTitle(note.title);
    setEditContent(note.transcript || note.extractedText || '');
    setIsEditing(true);
  };

  const handleSaveEdit = () => {
    const updates: Record<string, any> = { title: editTitle };
    if (note.type === 'text') {
      updates.extractedText = editContent;
    } else {
      updates.transcript = editContent;
    }
    updateNote(note.id, updates);
    setIsEditing(false);
    toast.success('Note updated');
  };

  const handleCancelEdit = () => {
    setIsEditing(false);
    setEditTitle('');
    setEditContent('');
  };

  const handleSaveChatInsight = (content: string) => {
    const currentInsights = note.chatInsights || [];
    updateNote(note.id, {
      chatInsights: [...currentInsights, content]
    });
  };

  const handleExportMarkdown = () => {
    const content = `# ${note.title}

**Type:** ${note.type}
**Created:** ${new Date(note.createdAt).toLocaleDateString()}

---

## Content

${note.transcript || note.extractedText || 'No content available'}

${note.summary ? `## Summary\n\n${note.summary}\n` : ''}

${note.actionItems?.length ? `## Action Items\n\n${note.actionItems.map((item, i) => `${i + 1}. ${item}`).join('\n')}\n` : ''}

${note.chatInsights?.length ? `## Insights from Chat\n\n${note.chatInsights.map((insight, i) => `- ${insight}`).join('\n\n')}\n` : ''}
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${note.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Note exported as Markdown');
  };

  const handleAssignFolder = (folderId: string | undefined) => {
    updateNote(note.id, { folderId });
    toast.success(folderId ? 'Note moved to folder' : 'Note removed from folder');
  };

  const handleToggleTag = (tagName: string) => {
    const currentTags = note.tags || [];
    const newTags = currentTags.includes(tagName)
      ? currentTags.filter(t => t !== tagName)
      : [...currentTags, tagName];
    updateNote(note.id, { tags: newTags });
    toast.success(currentTags.includes(tagName) ? 'Tag removed' : 'Tag added');
  };

  const noteContent = note.transcript || note.extractedText || '';
  const currentFolder = folders.find(f => f.id === note.folderId);

  // Auto-generate summary and action items on note load
  useEffect(() => {
    const autoGenerate = async () => {
      if (!noteContent || hasAutoGenerated.current) return;
      
      const needsSummary = !note.summary;
      const needsActions = !note.actionItems || note.actionItems.length === 0;
      
      if (!needsSummary && !needsActions) return;
      
      hasAutoGenerated.current = true;
      setIsAutoGenerating(true);
      
      try {
        const updates: Record<string, any> = {};
        
        if (needsSummary) {
          const summaryResult = await generateBriefSummary(noteContent);
          if (summaryResult.success && summaryResult.content) {
            updates.summary = summaryResult.content;
          }
        }
        
        if (needsActions) {
          const actionsResult = await generateActionItems(noteContent);
          if (actionsResult.success && actionsResult.content) {
            updates.actionItems = actionsResult.content.split('\n').filter((item) => item.trim());
          }
        }
        
        if (Object.keys(updates).length > 0) {
          updateNote(note.id, updates);
        }
      } catch (error) {
        console.error('Auto-generation error:', error);
      } finally {
        setIsAutoGenerating(false);
      }
    };
    
    autoGenerate();
  }, [note.id, noteContent, note.summary, note.actionItems, updateNote]);

  // Searchable transcript with highlighting
  const { highlightedContent, matchCount } = useMemo(() => {
    if (!transcriptSearch || !noteContent) {
      return { highlightedContent: noteContent, matchCount: 0 };
    }
    
    const regex = new RegExp(`(${transcriptSearch.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'gi');
    const matches = noteContent.match(regex);
    const highlighted = noteContent.replace(regex, '<mark class="bg-primary/30 text-foreground rounded px-0.5">$1</mark>');
    
    return { 
      highlightedContent: highlighted, 
      matchCount: matches?.length || 0 
    };
  }, [noteContent, transcriptSearch]);

  const handleReadAloud = () => {
    if (isPlaying) {
      stop();
    } else {
      const textToRead = note.summary || noteContent;
      if (textToRead) {
        speak(textToRead);
      } else {
        toast.error('No content to read');
      }
    }
  };

  return (
    <div className="p-6 max-w-6xl mx-auto animate-fade-in">
      {/* Header */}
      <div className="p-4 mb-6 rounded-xl glass-strong">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Button variant="ghost" onClick={() => navigate('/')} className="transition-transform hover:scale-105 hover-glow">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back
            </Button>
            <div className="w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center pulse-glow">
              <FileText className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h2 className="font-semibold text-lg line-clamp-1">{note.title}</h2>
              <p className="text-xs text-muted-foreground">
                {formatDistanceToNow(new Date(note.createdAt), { addSuffix: true })}
                {currentFolder && ` • ${currentFolder.name}`}
              </p>
            </div>
          </div>
        
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="icon" onClick={() => toggleStar(note.id)} className="transition-transform hover:scale-110">
            <Star className={`h-5 w-5 transition-all ${note.starred ? 'fill-primary text-primary scale-110' : ''}`} />
          </Button>
          
          {/* Folder Assignment */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="transition-transform hover:scale-110">
                <FolderOpen className={`h-5 w-5 ${currentFolder ? 'text-primary' : ''}`} />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="bg-popover border border-border z-50">
              <DropdownMenuItem onClick={() => handleAssignFolder(undefined)} className={!note.folderId ? 'bg-primary/10' : ''}>
                No Folder
              </DropdownMenuItem>
              <DropdownMenuSeparator />
              {folders.map(folder => (
                <DropdownMenuItem 
                  key={folder.id} 
                  onClick={() => handleAssignFolder(folder.id)}
                  className={note.folderId === folder.id ? 'bg-primary/10' : ''}
                >
                  <FolderOpen className="h-4 w-4 mr-2" />
                  {folder.name}
                </DropdownMenuItem>
              ))}
            </DropdownMenuContent>
          </DropdownMenu>

          {/* Tag Assignment */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="transition-transform hover:scale-110">
                <Hash className={`h-5 w-5 ${note.tags?.length ? 'text-primary' : ''}`} />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="bg-popover border border-border z-50">
              {tags.length === 0 ? (
                <div className="px-3 py-2 text-sm text-muted-foreground">No tags created</div>
              ) : (
                tags.map(tag => (
                  <DropdownMenuItem 
                    key={tag.id} 
                    onClick={() => handleToggleTag(tag.name)}
                    className={note.tags?.includes(tag.name) ? 'bg-primary/10' : ''}
                  >
                    <Hash className="h-4 w-4 mr-2" />
                    {tag.name}
                    {note.tags?.includes(tag.name) && <span className="ml-auto">✓</span>}
                  </DropdownMenuItem>
                ))
              )}
            </DropdownMenuContent>
          </DropdownMenu>

          <Button variant="ghost" size="icon" className="transition-transform hover:scale-110">
            <Share className="h-5 w-5" />
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="transition-transform hover:scale-110">
                <Download className="h-5 w-5" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onClick={handleExportMarkdown}>
                <FileText className="h-4 w-4 mr-2" />
                Export as Markdown
              </DropdownMenuItem>
              {(note.sourceUrl || note.storageKey) && (
                <DropdownMenuItem onClick={() => {
                  const url = note.sourceUrl || note.storageKey;
                  if (url) {
                    // If it's a blob URL or data URL, create download link
                    if (url.startsWith('blob:') || url.startsWith('data:')) {
                      const a = document.createElement('a');
                      a.href = url;
                      a.download = `${note.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.${note.type === 'audio' ? 'webm' : note.type === 'pdf' ? 'pdf' : 'file'}`;
                      document.body.appendChild(a);
                      a.click();
                      document.body.removeChild(a);
                    } else {
                      // Open S3/external URL in new tab for download
                      window.open(url, '_blank');
                    }
                    toast.success('Downloading original file');
                  }
                }}>
                  <Download className="h-4 w-4 mr-2" />
                  Download Original {note.type === 'audio' ? 'Audio' : note.type === 'pdf' ? 'PDF' : 'File'}
                </DropdownMenuItem>
              )}
            </DropdownMenuContent>
          </DropdownMenu>
          <Button variant="ghost" size="icon" onClick={handleDelete} className="transition-transform hover:scale-110">
            <Trash2 className="h-5 w-5 text-destructive" />
          </Button>
          
          {/* Save to Knowledge Base */}
          <Button
            variant={note.inKnowledgeBase ? 'default' : 'outline'}
            size="sm"
            onClick={() => {
              updateNote(note.id, { inKnowledgeBase: !note.inKnowledgeBase });
              toast.success(note.inKnowledgeBase ? 'Removed from Knowledge Base' : 'Added to Knowledge Base');
            }}
            className="transition-transform hover:scale-105 gap-1 hover-glow"
          >
            <Brain className="h-4 w-4" />
            {note.inKnowledgeBase ? 'In KB' : 'Save to KB'}
          </Button>
        </div>
        </div>
      </div>

      {/* Title & Meta */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2 flex-wrap">
          <Badge variant="secondary" className="uppercase text-xs">
            {note.type}
          </Badge>
          {currentFolder && (
            <Badge variant="outline" className="gap-1">
              <FolderOpen className="h-3 w-3" />
              {currentFolder.name}
            </Badge>
          )}
          {note.tags?.map(tag => (
            <Badge key={tag} variant="outline" className="gap-1">
              <Hash className="h-3 w-3" />
              {tag}
            </Badge>
          ))}
          {note.status === 'processing' && (
            <Badge variant="outline" className="gap-1">
              <Loader2 className="h-3 w-3 animate-spin" />
              Processing
            </Badge>
          )}
          <span className="text-sm text-muted-foreground">
            {formatDistanceToNow(new Date(note.createdAt), { addSuffix: true })}
          </span>
        </div>
        {isEditing ? (
          <div className="flex items-center gap-2">
            <Input
              value={editTitle}
              onChange={(e) => setEditTitle(e.target.value)}
              className="text-2xl font-bold h-12"
              placeholder="Note title"
            />
            <Button size="icon" onClick={handleSaveEdit} className="shrink-0">
              <Save className="h-4 w-4" />
            </Button>
            <Button size="icon" variant="ghost" onClick={handleCancelEdit} className="shrink-0">
              <XCircle className="h-4 w-4" />
            </Button>
          </div>
        ) : (
          <div className="flex items-center gap-2">
            <h1 className="text-3xl font-bold">{note.title}</h1>
            <Button size="icon" variant="ghost" onClick={handleStartEdit} className="shrink-0">
              <Pencil className="h-4 w-4" />
            </Button>
          </div>
        )}
      </div>

      {/* Content Area */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Source & Transcript */}
        <div className="space-y-6">
          <SourcePreview note={note} />

          <div className="rounded-xl bg-card border border-border overflow-hidden">
            <div className="p-4 border-b border-border space-y-3">
              <div className="flex items-center justify-between">
                <h3 className="font-semibold">Transcript / Content</h3>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleReadAloud}
                  disabled={isTTSLoading || !noteContent}
                  className="h-8"
                >
                  {isPlaying ? (
                    <>
                      <VolumeX className="h-4 w-4 mr-1" />
                      Stop
                    </>
                  ) : (
                    <>
                      <Volume2 className="h-4 w-4 mr-1" />
                      {isTTSLoading ? 'Loading...' : 'Read Aloud'}
                    </>
                  )}
                </Button>
              </div>
              {/* Search within transcript */}
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search in transcript..."
                  value={transcriptSearch}
                  onChange={(e) => setTranscriptSearch(e.target.value)}
                  className="pl-9 pr-16 h-9"
                />
                {transcriptSearch && (
                  <div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-1">
                    <span className="text-xs text-muted-foreground">{matchCount} found</span>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-6 w-6"
                      onClick={() => setTranscriptSearch('')}
                    >
                      <X className="h-3 w-3" />
                    </Button>
                  </div>
                )}
              </div>
            </div>
            <ScrollArea className="h-[300px]">
              <div className="p-4">
                {isEditing ? (
                  <Textarea
                    value={editContent}
                    onChange={(e) => setEditContent(e.target.value)}
                    className="min-h-[250px] text-sm"
                    placeholder="Enter note content..."
                  />
                ) : noteContent ? (
                  <p 
                    className="text-sm text-muted-foreground whitespace-pre-wrap"
                    dangerouslySetInnerHTML={{ __html: highlightedContent }}
                  />
                ) : (
                  <p className="text-sm text-muted-foreground italic">
                    No content extracted yet. 
                    {note.type === 'youtube' && ' YouTube transcript extraction coming soon.'}
                    {note.type === 'audio' && ' Audio transcription will appear here after processing.'}
                    {note.type === 'image' && ' OCR text extraction coming soon.'}
                  </p>
                )}
              </div>
            </ScrollArea>
          </div>
        </div>

        {/* Right: AI Outputs */}
        <div className="space-y-6">
          <div className="rounded-xl bg-card border border-border overflow-hidden">
            <Tabs value={activeTab} onValueChange={setActiveTab}>
              <div className="border-b border-border px-4">
                <TabsList className="bg-transparent h-12">
                  <TabsTrigger value="overview">Overview</TabsTrigger>
                  <TabsTrigger value="templates">AI Templates</TabsTrigger>
                  <TabsTrigger value="chat">Chat</TabsTrigger>
                </TabsList>
              </div>

              <div className="p-4">
                <TabsContent value="overview" className="m-0">
                  <ScrollArea className="h-[400px]">
                    <div className="space-y-4 pr-4">
                      {/* Summary */}
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <h4 className="font-medium">Summary</h4>
                          {note.summary && (
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => isPlaying ? stop() : speak(note.summary!)}
                              disabled={isTTSLoading}
                              className="h-7 text-xs"
                            >
                              {isPlaying ? <VolumeX className="h-3 w-3 mr-1" /> : <Volume2 className="h-3 w-3 mr-1" />}
                              {isPlaying ? 'Stop' : 'Read'}
                            </Button>
                          )}
                        </div>
                        <p className="text-sm text-muted-foreground">
                          {note.summary || 'Generate a summary using AI Templates.'}
                        </p>
                      </div>

                      {/* Action Items */}
                      <div>
                        <h4 className="font-medium mb-2">Action Items</h4>
                        {note.actionItems && note.actionItems.length > 0 ? (
                          <ul className="space-y-2">
                            {note.actionItems.map((item, i) => (
                              <li key={i} className="flex items-start gap-2 text-sm">
                                <span className="w-5 h-5 rounded-full bg-primary/20 text-primary flex items-center justify-center text-xs shrink-0 mt-0.5">
                                  {i + 1}
                                </span>
                                <span>{item}</span>
                              </li>
                            ))}
                          </ul>
                        ) : (
                          <p className="text-sm text-muted-foreground">
                            Extract action items using AI Templates.
                          </p>
                        )}
                      </div>

                      {/* Bulleted Notes */}
                      {note.bulletedNotes && (
                        <div>
                          <h4 className="font-medium mb-2">Bulleted Notes</h4>
                          <div className="prose prose-sm dark:prose-invert max-w-none">
                            <ReactMarkdown
                              components={{
                                strong: ({ children }) => <strong className="font-bold text-foreground">{children}</strong>,
                                ul: ({ children }) => <ul className="list-disc pl-4 space-y-1">{children}</ul>,
                                ol: ({ children }) => <ol className="list-decimal pl-4 space-y-1">{children}</ol>,
                                li: ({ children }) => <li className="text-sm text-muted-foreground">{children}</li>,
                                p: ({ children }) => <p className="text-sm text-muted-foreground mb-2">{children}</p>,
                              }}
                            >
                              {note.bulletedNotes}
                            </ReactMarkdown>
                          </div>
                        </div>
                      )}

                      {/* Meeting Minutes */}
                      {note.meetingMinutes && (
                        <div>
                          <h4 className="font-medium mb-2">Meeting Minutes</h4>
                          <div className="prose prose-sm dark:prose-invert max-w-none">
                            <ReactMarkdown
                              components={{
                                strong: ({ children }) => <strong className="font-bold text-foreground">{children}</strong>,
                                ul: ({ children }) => <ul className="list-disc pl-4 space-y-1">{children}</ul>,
                                ol: ({ children }) => <ol className="list-decimal pl-4 space-y-1">{children}</ol>,
                                li: ({ children }) => <li className="text-sm text-muted-foreground">{children}</li>,
                                p: ({ children }) => <p className="text-sm text-muted-foreground mb-2">{children}</p>,
                              }}
                            >
                              {note.meetingMinutes}
                            </ReactMarkdown>
                          </div>
                        </div>
                      )}

                      {/* Follow-up Email */}
                      {note.followUpEmail && (
                        <div>
                          <h4 className="font-medium mb-2">Follow-up Email</h4>
                          <div className="prose prose-sm dark:prose-invert max-w-none">
                            <ReactMarkdown
                              components={{
                                strong: ({ children }) => <strong className="font-bold text-foreground">{children}</strong>,
                                ul: ({ children }) => <ul className="list-disc pl-4 space-y-1">{children}</ul>,
                                ol: ({ children }) => <ol className="list-decimal pl-4 space-y-1">{children}</ol>,
                                li: ({ children }) => <li className="text-sm text-muted-foreground">{children}</li>,
                                p: ({ children }) => <p className="text-sm text-muted-foreground mb-2">{children}</p>,
                              }}
                            >
                              {note.followUpEmail}
                            </ReactMarkdown>
                          </div>
                        </div>
                      )}

                      {/* Quiz Content */}
                      {note.quizContent && (
                        <div>
                          <h4 className="font-medium mb-2">Quiz Questions</h4>
                          <div className="prose prose-sm dark:prose-invert max-w-none">
                            <ReactMarkdown
                              components={{
                                strong: ({ children }) => <strong className="font-bold text-foreground">{children}</strong>,
                                ul: ({ children }) => <ul className="list-disc pl-4 space-y-1">{children}</ul>,
                                ol: ({ children }) => <ol className="list-decimal pl-4 space-y-1">{children}</ol>,
                                li: ({ children }) => <li className="text-sm text-muted-foreground">{children}</li>,
                                p: ({ children }) => <p className="text-sm text-muted-foreground mb-2">{children}</p>,
                              }}
                            >
                              {note.quizContent}
                            </ReactMarkdown>
                          </div>
                        </div>
                      )}

                      {/* Chat Insights */}
                      {note.chatInsights && note.chatInsights.length > 0 && (
                        <div>
                          <h4 className="font-medium mb-2 flex items-center gap-2">
                            <Lightbulb className="h-4 w-4 text-primary" />
                            Saved Insights
                          </h4>
                          <div className="space-y-2">
                            {note.chatInsights.map((insight, i) => (
                              <div key={i} className="p-3 rounded-lg bg-muted text-sm">
                                {insight}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {/* Auto-generating indicator */}
                      {isAutoGenerating && (
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <Loader2 className="h-4 w-4 animate-spin" />
                          Generating summary and action items...
                        </div>
                      )}
                    </div>
                  </ScrollArea>
                </TabsContent>

                <TabsContent value="templates" className="m-0">
                  <AITemplatesPanel
                    noteContent={noteContent}
                    onSaveOutput={handleSaveAIOutput}
                  />
                </TabsContent>

                <TabsContent value="chat" className="m-0">
                  <NoteChat 
                    noteContent={noteContent} 
                    noteTitle={note.title}
                    onSaveInsight={handleSaveChatInsight}
                  />
                </TabsContent>
              </div>
            </Tabs>
          </div>
        </div>
      </div>
    </div>
  );
};

export default NoteDetail;
